# Add main1_1.cpp after main in order to have it as a pre-requisite
p1: main1_1.cpp
	g++ main1_1.cpp -o day1_2015_pt1

p2: main1_2.cpp
	g++ main1_2.cpp -o day1_2015_pt2

clean:
	rm day1_2015_pt1 day1_2015_pt2
